/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(channel_phase.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d1af55dcf6ae9a28bae1bc0d6cbc84f7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/usrp_ble/channel_phase.h>
// pydoc.h is automatically generated in the build directory
#define D(...) ""

void bind_channel_phase(py::module& m)
{

    using channel_phase    = gr::usrp_ble::channel_phase;


    py::class_<channel_phase, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<channel_phase>>(m, "channel_phase", D(channel_phase))

        .def(py::init(&channel_phase::make),
           py::arg("center_freq_hz"),
           py::arg("distance_m"),
           py::arg("amplitude"),
           D(channel_phase,make)
        )
        .def("set_center_freq_hz", &channel_phase::set_center_freq_hz,
            py::arg("center_freq_hz"),
            D(channel_phase,set_center_freq_hz)
        )
        .def("set_distance_m", &channel_phase::set_distance_m,
            py::arg("distance_m"),
            D(channel_phase,set_distance_m)
        )
        .def("set_amplitude", &channel_phase::set_amplitude,
            py::arg("amplitude"),
            D(channel_phase,set_amplitude)
        )
        



        ;




}






