/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(data_send.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3c51d638b5bbdc5c49008882c745e750)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/usrp_ble/data_send.h>
// pydoc.h is automatically generated in the build directory
//#include <data_send_pydoc.h>
#define D(...) ""

void bind_data_send(py::module& m)
{

    using data_send    = gr::usrp_ble::data_send;


    py::class_<data_send, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<data_send>>(m, "data_send", D(data_send))

        .def(py::init(&data_send::make),
           py::arg("sample_rate"),
           py::arg("bit_duration"),
           D(data_send,make)
        )
        .def("set_sample_rate", &data_send::set_sample_rate,
            py::arg("sample_rate"),
            D(data_send,set_sample_rate)
        )
        .def("set_bit_duration", &data_send::set_bit_duration,
            py::arg("bit_duration"),
            D(data_send,set_bit_duration)
        )
        



        ;




}








