/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(data_store.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e3283889ef90560c41e83c84cf877cda)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/usrp_ble/data_store.h>
// pydoc.h is automatically generated in the build directory
//#include <data_store_pydoc.h>
#define D(...) ""

void bind_data_store(py::module& m)
{

    using data_store    = gr::usrp_ble::data_store;


    py::class_<data_store, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<data_store>>(m, "data_store", D(data_store))

        .def(py::init(&data_store::make),
           py::arg("data_len"),
           py::arg("skip_len"),
           py::arg("path"),
           D(data_store,make)
        )
        



        ;




}






