/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(interact_center.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(26dd5c3f7ed1f3ecc039b0b60a11c1f8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/usrp_ble/interact_center.h>
// pydoc.h is automatically generated in the build directory
//#include <interact_center_pydoc.h>
#define D(...) ""

void bind_interact_center(py::module& m)
{

    using interact_center    = gr::usrp_ble::interact_center;


    py::class_<interact_center, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<interact_center>>(m, "interact_center", D(interact_center))

        .def(py::init(&interact_center::make),
           py::arg("sample_rate"),
           py::arg("start_btn"),
           py::arg("stop_btn"),
           py::arg("wait_time_ms"),
           py::arg("repeat_total"),
           D(interact_center,make)
        )
        .def("set_start_btn", &interact_center::set_start_btn,
            py::arg("start_btn"),
            D(interact_center,set_start_btn)
        )
        .def("set_stop_btn", &interact_center::set_stop_btn,
            py::arg("stop_btn"),
            D(interact_center,set_stop_btn)
        )
        .def("set_wait_time_ms", &interact_center::set_wait_time_ms,
            py::arg("wait_time_ms"),
            D(interact_center,set_wait_time_ms)
        )
        



        ;




}






