/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tx_rx_triggle.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e5593c7eaa8075ec432666f94901f084)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/usrp_ble/tx_rx_triggle.h>
// pydoc.h is automatically generated in the build directory
#include <tx_rx_triggle_pydoc.h>

void bind_tx_rx_triggle(py::module& m)
{

    using tx_rx_triggle    = gr::usrp_ble::tx_rx_triggle;


    py::class_<tx_rx_triggle, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<tx_rx_triggle>>(m, "tx_rx_triggle", D(tx_rx_triggle))

        .def(py::init(&tx_rx_triggle::make),
           D(tx_rx_triggle,make)
        )
        



        ;




}








