/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-usrp_ble
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_USRP_BLE_API_H
#define INCLUDED_USRP_BLE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_usrp_ble_EXPORTS
#define USRP_BLE_API __GR_ATTR_EXPORT
#else
#define USRP_BLE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_USRP_BLE_API_H */
